version: '3'

services:
  base:
    build:
      context: ./debian_config/
    image: mike/debian_config
    container_name: base
  m23:
    build: ./m23_config/
    image: mike/m23_config
    depends_on:
      - base
    ports:
      - "8080:80"
      - "4306:3306"
    volumes:
#       - /Path/To/Your/magento/magento2-dev-dk/instances:/var/www/html/shared
       - /Users/molochko/Sites/magento/magento2-dev-dk/instances:/var/www/html/shared
    tty: true
    container_name: m23